CREATE TABLE IF NOT EXISTS ACTORS(
    id BIGINT(19) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS MOVIES(
    id BIGINT(19) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    release_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    UNIQUE (name, release_date)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS MOVIE_AND_ACTORS(
    actor_id BIGINT(19) NOT NULL,
    movie_id BIGINT(19) NOT NULL,
    FOREIGN KEY (actor_id) REFERENCES actors(id),
    FOREIGN KEY (movie_id) REFERENCES movies(id),
    UNIQUE (actor_id, movie_id)
) ENGINE=INNODB;